
services:
  service-registry:
    build:
      context: ./ServiceRegistry
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - application-network

  workflow-service:
    build:
      context: ./WorkFlowIpVaptService
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - application-network
      - workflow-service-db-network
    depends_on:
      - service-registry

  notification-service:
    build:
      context: ./NotificationMicroservice
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
    networks:
      - application-network
      - notification-service-db-network
    depends_on:
      - service-registry
      - notification-service-db
  
  renewal-service:
    build:
      context: ./RenewalAndTransferMicroService
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
    networks:
      - application-network
      - renewal-service-db-network
    depends_on:
      - service-registry
      - renewal-service-db
    
  user-management-service:
    build:
      context: ./UserManagementMicroservice/server
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
    networks:
      - application-network
      - user-management-service-db-network
      - ldap-net
    depends_on:
      - service-registry
      - user-management-service-db
      - openldap


  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - application-network
    depends_on:
      - service-registry

  
  sonarqube:
    image: 4f01870f15a6
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs


  workflow-service-db:
    image: postgres:16-alpine3.21
    container_name: workflow_db
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=workflow_db
    volumes:
      - workflow-service-db-volume:/var/lib/postgresql/data
    networks:
      - workflow-service-db-network
  
  notification-service-db:
    image: postgres:16-alpine3.21
    container_name: notification_db
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=notification_db
    volumes:
      - notification-service-db-volume:/var/lib/postgresql/data
    networks:
      - notification-service-db-network
  
  renewal-service-db:
    image: postgres:16-alpine3.21
    container_name: renewal_db
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=renewal_db
    volumes:
      - renewal-service-db-volume:/var/lib/postgresql/data
    networks:
      - renewal-service-db-network

  user-management-service-db:
    image: postgres:16-alpine3.21
    container_name: user_management_db
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=user_management_db
    volumes:
      - user-management-service-db-volume:/var/lib/postgresql/data
    networks:
      - user-management-service-db-network

  openldap:
    image: versatile7programmer/my-cdac-ldap:latest
    container_name: ldap-server
    environment:
      - LDAP_ADMIN_PASSWORD:"raju"
      - LDAP_CONFIG_ADMIN_PASSWORD:"raju"
      - LDAP_ROOT:"dc=cdac,dc=in,dc=world"
    ports:
      - "1389:1389"
      - "389:389"    # Standard LDAP
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  
    networks:
      - ldap-net
    restart: unless-stopped
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  workflow-service-db-volume:
  notification-service-db-volume:
  renewal-service-db-volume:
  user-management-service-db-volume:
  ldap_data:
  ldap_config:


networks:
  application-network:
    driver: bridge
  workflow-service-db-network:
    driver: bridge
  notification-service-db-network:
    driver: bridge
  renewal-service-db-network:
    driver: bridge
  user-management-service-db-network:
    driver: bridge
  ldap-net:
    driver: bridge
  