
services:
  service-registry:
    build:
      context: ./ServiceRegistry
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - application-network

  workflow-service:
    build:
      context: ./WorkFlowIpVaptService
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - application-network
      - workflow-service-db-network
    depends_on:
      - service-registry

  notification-service:
    build:
      context: ./NotificationMicroservice
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - application-network
      - notification-service-db-network
    depends_on:
      - service-registry
  
  renewal-service:
    build:
      context: ./RenewalAndTransferMicroService
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - application-network
      - renewal-service-db-network
    depends_on:
      - service-registry
    
  user-management-service:
    build:
      context: ./UserManagementMicroservice
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - application-network
      - user-management-service-db-network
    depends_on:
      - service-registry

  
  sonarqube:
    image: 4f01870f15a6
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs


  workflow-service-db:
    image: postgres:16-alpine3.21
    container_name: postgres_workflow_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rishi
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=workflow_db
    volumes:
      - workflow-service-db-volume: /var/lib/postgresql/data
    networks:
      - workflow-service-db-network
  
  notification-service-db:
    image: postgres:16-alpine3.21
    container_name: postgres_workflow_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=raj
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=notification_db
    volumes:
      - notification-service-db-volume: /var/lib/postgresql/data
    networks:
      - notification-service-db-network
  
  renewal-service-db:
    image: postgres:16-alpine3.21
    container_name: postgres_workflow_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hansraj
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=renewal_db
    volumes:
      - renewal-service-db-volume: /var/lib/postgresql/data
    networks:
      - renewal-service-db-network

  user-management-service-db:
    image: postgres:16-alpine3.21
    container_name: postgres_workflow_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=raj
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=user_management_db
    volumes:
      - user-management-service-db-volume: /var/lib/postgresql/data
    networks:
      - user-management-service-db-network


volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  workflow-service-db-volume:
  notification-service-db-volume:
  renewal-service-db-volume:
  user-management-service-db-volume:


networks:
  application-network:
    driver: bridge
  workflow-service-db-network:
    driver: bridge
  notification-service-db-network:
    driver: bridge
  renewal-service-db-network:
    driver: bridge
  user-management-service-db-network:
    driver: bridge
  