global:
  scrape_interval: 15s # How frequently to scrape targets by default

scrape_configs:
  # Job to scrape Prometheus itself (optional, good for monitoring Prometheus)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job to scrape the Pushgateway
  # - job_name: 'pushgateway'
  #   honor_labels: true # Important! Use labels from Pushgateway, don't override them
  #   static_configs:
  #     # Replace <pushgateway_address> with the IP/hostname of your Pushgateway
  #     - targets: ['localhost:9091']
  - job_name: 'eureka'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:8761/eureka'
    relabel_configs:
      # Replace metrics path with metadata value from Eureka
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      # Combine IP and port
      # - source_labels: [__meta_eureka_instance_ip_addr, __meta_eureka_instance_port]
      #   separator: ":"
      #   target_label: __address__
      #   action: replace
      # # Optional: Rename job label to something nicer
      # - source_labels: [__meta_eureka_app_name]
      #   action: replace
      #   target_label: job
    